import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ContextProvider } from "./_components/ContextProvider";
import Header from "./_components/Header";

import QueryProvider from "./_components/QueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Decentralised todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <QueryProvider>
          <ContextProvider>
            <div className="bg-[rgb(235, 180, 16)]">
              <Header />
              {children}
            </div>
          </ContextProvider>
        </QueryProvider>

        {/* Add ReactQueryDevtools with initialIsOpen set to true */}
      </body>
    </html>
  );
}
