import { Metadata } from "next";
import { Inter } from "next/font/google"; // Importing Google Fonts
import "./globals.css";
import { ContextProvider } from "./_components/ContextProvider";
import Header from "./_components/Header";

import QueryProvider from "./_components/QueryProvider";
import Toast from "./_components/Toast";

// Load the Roboto font (You can also adjust the weights as needed)
const roboto = Inter({
  subsets: ["latin"],
  weights: ["100", "400", "700"], // You can change these depending on your needs
});

export const metadata: Metadata = {
  title: "Decentralised todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <QueryProvider>
          <ContextProvider>
            <div className="">
              <Header />
              {children}
            </div>
            <Toast />
          </ContextProvider>
        </QueryProvider>

        {/* Add ReactQueryDevtools with initialIsOpen set to true */}
      </body>
    </html>
  );
}
